-- =============================================================================
-- File: 0011_ux_copy_refinement.sql
-- Purpose: User-facing display copy for all 76 Drive services (ux-copy refined)
-- Source: docs/service-ux-copy-refined.json
-- Prerequisite: 0010_seed_listing_attributes.sql
-- Safe to re-run: YES
-- Rules: Preserves slug/keys/IDs. Updates display fields only.
-- =============================================================================

BEGIN;

UPDATE discovery.submarketplaces SET tagline = CASE slug
  WHEN 'transform' THEN 'Plan smarter, automate wisely, and stay aligned with strategy'
  WHEN 'enable' THEN 'Everyday people, finance, facilities, and IT support in one place'
  WHEN 'commercial' THEN 'Win attention, grow pipeline, and build lasting partnerships'
  WHEN 'delivery' THEN 'Onboard customers, deliver work, and keep operations running smoothly'
END
WHERE tenant_id = 'a0000000-0000-4000-8000-000000000001';

CREATE TEMP TABLE _ux_display (
  listing_id uuid PRIMARY KEY,
  service_name text NOT NULL,
  display_name text NOT NULL,
  short_description text NOT NULL,
  purpose text NOT NULL,
  when_to_use text[] NOT NULL,
  when_not_to_use text[] NOT NULL,
  required_inputs text[] NOT NULL
) ON COMMIT DROP;

INSERT INTO _ux_display (
  listing_id, service_name, display_name, short_description,
  purpose, when_to_use, when_not_to_use, required_inputs
) VALUES
  ('c0000000-0000-4000-8000-000000000001', 'Strategic Planning Support', 'Strategic planning help', 'Align your initiative with company strategy and get expert guidance.', 'Work with specialists to shape goals, scope, and outcomes for a programme or initiative.', ARRAY['You are starting a new initiative and need direction', 'You want help turning ideas into a clear plan'], ARRAY['You only need a document template', 'The plan is already approved'], ARRAY['Initiative name', 'What you need help with', 'Target date for decisions']),
  ('c0000000-0000-4000-8000-000000000002', 'Enterprise Architecture Review', 'Architecture review', 'Independent review of architecture for a major programme or change.', 'Have your architecture assessed before you commit to a large programme or platform change.', ARRAY['You are launching a major programme or platform change', 'You need sign-off on an architecture decision'], ARRAY['The change is small and already covered by existing standards', 'You only need an informal discussion with your lead'], ARRAY['Programme or change summary', 'Architecture documents or links', 'Review deadline']),
  ('c0000000-0000-4000-8000-000000000003', 'Platform Architecture Review', 'Platform design review', 'Review shared platform designs before multiple teams depend on them.', 'Get expert feedback on platform architecture and technical direction.', ARRAY['You are designing or changing a shared platform', 'More than one team will rely on the outcome'], ARRAY['The design was already reviewed and approved', 'Only one application is affected with no shared impact'], ARRAY['Platform or system name', 'Design documents or diagrams', 'Review deadline']),
  ('c0000000-0000-4000-8000-000000000004', 'Governance / Policy Exception', 'Policy exception', 'Request approval to depart from a standard policy or control.', 'Ask for a documented, time-bound exception when meeting a standard requirement is not possible.', ARRAY['You cannot comply with a policy or control in your situation', 'You need a formal waiver with a clear reason'], ARRAY['You can meet the requirement using existing approved options', 'You have not checked the relevant policy yet'], ARRAY['Policy or rule reference', 'Why an exception is needed', 'How you will reduce risk', 'How long the exception is needed']),
  ('c0000000-0000-4000-8000-000000000005', 'Risk & Compliance Assessment', 'Risk and compliance check', 'Formal assessment of risk and compliance for a change or engagement.', 'Understand regulatory, security, and compliance exposure before you proceed.', ARRAY['You are launching something with legal or security implications', 'A stakeholder asked for a formal risk view'], ARRAY['A recent assessment already covers this scope', 'You only need general policy guidance'], ARRAY['What is being assessed', 'Known risks or concerns', 'Required completion date']),
  ('c0000000-0000-4000-8000-000000000006', 'Benefits Realisation Review', 'Benefits progress review', 'Check whether expected benefits from an initiative are on track.', 'Review benefits tracking and evidence for an active initiative or stage gate.', ARRAY['You need to confirm benefits are being delivered', 'A milestone requires benefits evidence'], ARRAY['The initiative has not started yet', 'Benefits were never defined in the business case'], ARRAY['Initiative name', 'Benefits or KPIs to review', 'Review period or milestone']),
  ('c0000000-0000-4000-8000-000000000007', 'Innovation Intake', 'Submit an idea', 'Share a new idea for feedback and prioritisation.', 'Put forward an innovation idea and get guidance on next steps.', ARRAY['You have a new product, process, or improvement idea', 'You want feedback before investing further'], ARRAY['The idea is already funded and in delivery', 'You need automation built — use Process automation instead'], ARRAY['Idea summary', 'Problem it solves', 'Expected impact']),
  ('c0000000-0000-4000-8000-000000000008', 'AI Enablement Request', 'AI support for your team', 'Get help adopting AI for a specific use case.', 'Request guidance and enablement to use AI safely and effectively for a defined need.', ARRAY['You want to use AI for a clear business problem', 'You need help choosing approach, tools, or data'], ARRAY['You only need general awareness training', 'Your use case relies on unapproved data'], ARRAY['Use case description', 'Data involved', 'Target outcomes', 'Timeline']),
  ('c0000000-0000-4000-8000-000000000009', 'Process Automation Build', 'Automate a process', 'Design and build automation for a repeatable business process.', 'Replace manual steps with an automated workflow or bot for a stable, repeatable process.', ARRAY['The process is well understood and happens often', 'You have documented steps and owners'], ARRAY['The process is still changing', 'You need a one-off manual task completed'], ARRAY['Process name and steps', 'Systems involved', 'Expected volume', 'Target go-live date']),
  ('c0000000-0000-4000-8000-000000000010', 'Knowledge Engineering Request', 'Build a knowledge base', 'Create searchable, structured knowledge for your team.', 'Design and build a knowledge base or retrieval system so people can find answers quickly.', ARRAY['Important knowledge is scattered or hard to find', 'Your team needs a maintained knowledge hub'], ARRAY['You only need one article published', 'Source content is not approved yet'], ARRAY['Topic or domain', 'Source materials', 'Who will use it', 'What success looks like']),
  ('c0000000-0000-4000-8000-000000000011', 'Decision Intelligence / Analytics Request', 'Analytics for decisions', 'Dashboards, insights, or models to support a business decision.', 'Get analytics or decision-support built for a specific question or choice.', ARRAY['You need data to make a defined decision', 'Relevant data exists or can be identified'], ARRAY['You need a one-off report with no ongoing need', 'Required data is not approved for use'], ARRAY['Decision or question', 'Available data', 'Who needs the insight', 'Required date']),
  ('c0000000-0000-4000-8000-000000000012', 'Continuous Improvement Initiative', 'Improvement programme support', 'Expert help to start or run a continuous improvement effort.', 'Get advisory support to improve how a team or process performs over time.', ARRAY['You want structured improvement with sponsor support', 'You have a defined area to improve'], ARRAY['You need a single incident fixed', 'No one is assigned to lead the improvement'], ARRAY['Area to improve', 'Current problems', 'Sponsor name', 'Target start date']),
  ('c0000000-0000-4000-8000-000000000013', 'Pay Slip (download / request)', 'Pay slip', 'Get a copy of your pay slip when you cannot download it yourself.', 'Receive a pay slip by email or request when the self-service portal is unavailable.', ARRAY['You need a slip for a bank, visa, or third party', 'You cannot access the HR portal'], ARRAY['You can download your slip from the HR portal'], ARRAY['Pay period (month and year)', 'Reason', 'How you want it sent']),
  ('c0000000-0000-4000-8000-000000000014', 'Salary Certificate / Employment Letter', 'Salary or employment letter', 'Official letter confirming your employment or salary.', 'Request a formal letter for banks, landlords, or authorities that need proof of employment or pay.', ARRAY['A third party needs proof of employment or salary on letterhead', 'You need an official certificate'], ARRAY['Simple employment confirmation is enough — use Employment verification letter'], ARRAY['Purpose of the letter', 'Addressee (if known)', 'Required date', 'Any specific wording']),
  ('c0000000-0000-4000-8000-000000000015', 'Change Bank Account for Payroll', 'Update payroll bank account', 'Change the bank account where your salary is paid.', 'Update payroll with new bank details so your salary goes to the correct account.', ARRAY['You opened a new account for salary', 'Your bank details changed'], ARRAY['You only need expense reimbursement to a different account'], ARRAY['New bank name and account details', 'Effective date', 'Proof of account if requested']),
  ('c0000000-0000-4000-8000-000000000016', 'Leave Request (annual / sick / unpaid)', 'Book leave', 'Request annual, sick, or unpaid time off.', 'Submit leave and notify your manager through the official process.', ARRAY['You need time off and want it recorded', 'You are reporting sick leave'], ARRAY['Leave was already entered for you by HR'], ARRAY['Leave type', 'Start and end dates', 'Cover or handover plan']),
  ('c0000000-0000-4000-8000-000000000017', 'Leave Balance Query', 'Check leave balance', 'Find out how much leave you have left.', 'Get your current leave balance when the portal is unclear or unavailable.', ARRAY['You are planning time off', 'The balance shown online looks wrong'], ARRAY['Your balance is visible and correct in the HR portal'], ARRAY['Leave type (if specific)', 'Year or period']),
  ('c0000000-0000-4000-8000-000000000018', 'Work-From-Home / Remote Work Request', 'Remote work request', 'Request approval to work from home or remotely.', 'Ask for approved remote or hybrid working for a defined period.', ARRAY['You need to work away from the office for specific dates', 'Your role allows remote work with approval'], ARRAY['You need a permanent arrangement change — speak to your manager first'], ARRAY['Dates or pattern', 'Reason', 'Work location', 'Manager name']),
  ('c0000000-0000-4000-8000-000000000019', 'Timesheet / Attendance Correction', 'Fix timesheet or attendance', 'Correct a wrong or missing attendance record.', 'Update your timesheet or attendance when hours were recorded incorrectly.', ARRAY['Hours were logged wrong', 'A clock-in or clock-out is missing'], ARRAY['You need to change approved leave — use Book leave'], ARRAY['Date(s) affected', 'Correct hours or status', 'Reason']),
  ('c0000000-0000-4000-8000-000000000020', 'Overtime Request', 'Overtime approval', 'Request approval for overtime hours.', 'Get overtime recorded and approved for work outside your normal schedule.', ARRAY['You worked or will work extra hours', 'Your manager supports the claim'], ARRAY['Overtime is not allowed for your role without prior approval'], ARRAY['Date(s) and hours', 'Reason or project', 'Manager approval if already given']),
  ('c0000000-0000-4000-8000-000000000021', 'Hiring Requisition (raise a new role)', 'Open a new role', 'Start recruitment for an approved new position.', 'Raise a requisition so recruitment can begin for a new hire.', ARRAY['Headcount is approved and the role is defined', 'You need to start hiring'], ARRAY['You are moving someone internally — use Internal transfer', 'Headcount is not approved yet'], ARRAY['Role title and level', 'Department and location', 'Job description', 'Target start date']),
  ('c0000000-0000-4000-8000-000000000022', 'New Joiner Onboarding', 'Onboard a new joiner', 'Set up access, equipment, and day-one readiness for a new hire.', 'Coordinate onboarding so a new team member is ready to start.', ARRAY['A new hire has a confirmed start date', 'You are the hiring manager or coordinator'], ARRAY['The role requisition is not approved — open a new role first'], ARRAY['New joiner name and start date', 'Role and department', 'Equipment and access needs']),
  ('c0000000-0000-4000-8000-000000000023', 'Employment Verification Letter', 'Employment verification', 'Confirm your employment status for a third party.', 'Request a letter confirming you work here, without salary details.', ARRAY['A verifier needs employment confirmation only', 'Salary details are not required'], ARRAY['You need salary on the letter — use Salary or employment letter'], ARRAY['Purpose', 'Addressee', 'Required date']),
  ('c0000000-0000-4000-8000-000000000024', 'Role Transition / Internal Transfer', 'Internal transfer', 'Move to a new role or team within the company.', 'Process an internal role change, promotion, or transfer.', ARRAY['Your role, team, or manager is changing internally', 'Both managers agree in principle'], ARRAY['You are leaving the company — use Resignation and offboarding'], ARRAY['Current and new role', 'Effective date', 'Current and new manager', 'Reason']),
  ('c0000000-0000-4000-8000-000000000025', 'Offboarding / Resignation', 'Resignation and offboarding', 'Start the process when you or a team member is leaving.', 'Coordinate HR, access, and equipment steps when someone leaves.', ARRAY['Someone has resigned or is being offboarded', 'You need leaver steps coordinated'], ARRAY['You only need system access removed — use Remove leaver access'], ARRAY['Person leaving and last day', 'Reason if resignation', 'Manager name', 'Equipment to return']),
  ('c0000000-0000-4000-8000-000000000026', 'HR Case / Grievance', 'HR support case', 'Confidential help with a workplace or people matter.', 'Raise a sensitive HR matter for specialist, confidential support.', ARRAY['You need HR help with a people issue', 'The matter cannot be resolved with your manager alone'], ARRAY['You only need a policy explained — check help articles or ask HR informally'], ARRAY['Nature of the issue (high level)', 'People involved', 'What outcome you need', 'Whether you spoke to your manager']),
  ('c0000000-0000-4000-8000-000000000027', 'Learning / Training Enrolment', 'Enrol in training', 'Sign up for a course or learning programme.', 'Enrol yourself or a team member in approved training.', ARRAY['You have a course or programme to join', 'Training is required for your role'], ARRAY['You need a new course created — describe that in your request'], ARRAY['Course or programme name', 'Participant name(s)', 'Preferred dates', 'Business reason']),
  ('c0000000-0000-4000-8000-000000000028', 'Request New Tool / Software', 'New software or tool', 'Request a new application or subscription for your work.', 'Ask for software or a tool that is not in the standard catalogue.', ARRAY['You need an app that is not already available', 'Your team needs a new subscription'], ARRAY['The tool is already available — request access instead'], ARRAY['Tool or product name', 'Vendor if known', 'Why you need it', 'Start date']),
  ('c0000000-0000-4000-8000-000000000029', 'Request Tool Privileges / Elevated Access', 'Extra system access', 'Request higher permissions for a system you already use.', 'Get elevated or admin access for a defined task and time period.', ARRAY['Your work requires higher permissions', 'You need temporary admin access'], ARRAY['Standard access is enough'], ARRAY['System name', 'Access level needed', 'Duration', 'Business reason']),
  ('c0000000-0000-4000-8000-000000000030', 'Software License Upgrade', 'Upgrade software license', 'Change or renew a software license.', 'Upgrade, add seats, or renew a software license.', ARRAY['You need more seats or a higher tier', 'A renewal needs action'], ARRAY['You need entirely new software — use New software or tool'], ARRAY['Product name', 'Current and requested license', 'Number of users', 'Effective or renewal date']),
  ('c0000000-0000-4000-8000-000000000031', 'Hardware / Device Request', 'Laptop or device', 'Request a laptop, monitor, phone, or other device.', 'Get hardware for a new role, replacement, or upgrade.', ARRAY['You need new or replacement equipment', 'Your device is faulty or end of life'], ARRAY['You only need a password reset'], ARRAY['Device type', 'Reason', 'Preferred specification', 'Delivery location']),
  ('c0000000-0000-4000-8000-000000000032', 'Account / Password Reset', 'Reset password', 'Unlock your account or reset a forgotten password.', 'Regain access when self-service reset does not work or your account is locked.', ARRAY['You cannot sign in', 'Self-service reset failed or account is locked'], ARRAY['You never had access to this system — request new access instead'], ARRAY['System name', 'Your username or email', 'Contact number']),
  ('c0000000-0000-4000-8000-000000000033', 'VPN / Remote Access', 'Remote network access', 'Set up secure access to work systems from outside the office.', 'Get VPN or remote access so you can work securely off-site.', ARRAY['You need to connect to company networks from outside the office', 'Your remote access expired'], ARRAY['You only need access to one application — request that app directly'], ARRAY['Device you will use', 'Country or location', 'Duration needed', 'Manager name']),
  ('c0000000-0000-4000-8000-000000000034', 'Access Deprovisioning (leaver)', 'Remove leaver access', 'Turn off system access when someone leaves or changes role.', 'Remove accounts and access for a leaver or role change on the agreed date.', ARRAY['Someone is leaving or moving roles', 'Access must be removed on a set date'], ARRAY['You need to change your own access'], ARRAY['Person name', 'Last day or effective date', 'Systems to remove', 'Confirming manager']),
  ('c0000000-0000-4000-8000-000000000035', 'Operational Reporting Request', 'Operations report', 'Request a workforce or operations report.', 'Get a report that is not available in self-service dashboards.', ARRAY['You need data for a decision or audit', 'The report is not in existing dashboards'], ARRAY['The data is already in a dashboard you can access'], ARRAY['Report description', 'Period covered', 'Format needed', 'Required date']),
  ('c0000000-0000-4000-8000-000000000036', 'Performance Review Setup', 'Set up performance reviews', 'Configure a review cycle for your team.', 'Set up templates, timelines, and system settings for performance reviews.', ARRAY['You are launching reviews for a team', 'You need HR to configure the cycle'], ARRAY['You are asking about your own review date — ask your manager'], ARRAY['Team or department', 'Review period', 'Template to use', 'Launch date']),
  ('c0000000-0000-4000-8000-000000000037', 'Quality Audit Request', 'Quality audit', 'Independent quality check of a process or deliverable.', 'Request a quality audit or review before a milestone or for evidence.', ARRAY['You need an independent quality check', 'A customer or audit requires evidence'], ARRAY['You need a single bug fixed — log an incident instead'], ARRAY['Scope of audit', 'Standard or checklist to apply', 'Requested date', 'Sponsor']),
  ('c0000000-0000-4000-8000-000000000038', 'Service Request / Incident Logging', 'Log an incident', 'Report something broken or blocked in day-to-day operations.', 'Create a tracked ticket for an operational issue so it can be resolved.', ARRAY['Something is not working in daily operations', 'You need a reference number for follow-up'], ARRAY['You need customer delivery support — use Customer support case'], ARRAY['What happened', 'Impact', 'When it started', 'System or process affected']),
  ('c0000000-0000-4000-8000-000000000039', 'Procurement / Purchase Request', 'Buy something', 'Submit a purchase request for goods or services.', 'Start procurement for an approved purchase within budget.', ARRAY['You need to buy something with approved budget', 'You have a quote or supplier in mind'], ARRAY['Spend exceeds your approval limit — confirm with finance first'], ARRAY['What you are buying', 'Supplier if known', 'Estimated cost', 'Cost centre', 'Required date']),
  ('c0000000-0000-4000-8000-000000000040', 'Vendor Onboarding', 'Add a new supplier', 'Register a new vendor in finance systems.', 'Onboard a supplier so you can pay them and place orders.', ARRAY['You selected a new supplier', 'Contract is signed or nearly ready'], ARRAY['The supplier is already registered'], ARRAY['Supplier legal name', 'Contact details', 'Services provided', 'Contract reference if any']),
  ('c0000000-0000-4000-8000-000000000041', 'Contract Review / Setup', 'Contract review', 'Draft or review a commercial agreement.', 'Get a contract reviewed, drafted, or set up in systems.', ARRAY['A new agreement needs review', 'Terms changed from the standard template'], ARRAY['You are using an unchanged standard template'], ARRAY['Other party name', 'Contract type and value', 'Key terms', 'Target signature date']),
  ('c0000000-0000-4000-8000-000000000042', 'Legal Review Request', 'Legal review', 'Legal sign-off on a document or question.', 'Ask legal to review a document or advise on legal risk.', ARRAY['A document needs legal approval before you commit', 'You are unsure about legal risk'], ARRAY['The question is purely about payment timing — use Invoice query'], ARRAY['Document type and link', 'Your question or concern', 'Decision deadline', 'Business owner']),
  ('c0000000-0000-4000-8000-000000000043', 'Expense Reimbursement', 'Expense claim', 'Claim back money you spent on approved business costs.', 'Submit expenses for reimbursement with receipts.', ARRAY['You paid business costs yourself', 'You have receipts and policy-compliant spend'], ARRAY['The expense should go on a company card'], ARRAY['Dates and amounts', 'Category', 'Receipts', 'Cost centre or project']),
  ('c0000000-0000-4000-8000-000000000044', 'Petty Cash Request', 'Petty cash', 'Petty cash advance or top-up for small office purchases.', 'Request petty cash for immediate small purchases within limits.', ARRAY['Your team uses a petty cash float', 'You need cash for small urgent buys'], ARRAY['The amount exceeds petty cash limits — use Buy something'], ARRAY['Amount', 'Purpose', 'Cost centre', 'Custodian name']),
  ('c0000000-0000-4000-8000-000000000045', 'Invoice / Payment Query', 'Invoice or payment question', 'Ask about invoice status or when payment will be made.', 'Get an update on an invoice or payment timing.', ARRAY['An invoice is overdue or status is unclear', 'A supplier is asking about payment'], ARRAY['You need to submit a new invoice for payment'], ARRAY['Invoice or PO number', 'Supplier name', 'Amount and date', 'Your question']),
  ('c0000000-0000-4000-8000-000000000046', 'Tax / Year-End Statement', 'Tax or year-end statement', 'Request tax certificates or year-end financial documents.', 'Get official tax or year-end statements for personal or compliance use.', ARRAY['You need a tax certificate or year-end summary', 'An authority requires official documents'], ARRAY['You need a salary letter — use Salary or employment letter'], ARRAY['Document type', 'Tax year', 'Purpose', 'Required date']),
  ('c0000000-0000-4000-8000-000000000047', 'Salary Advance / Loan Request', 'Salary advance or loan', 'Request a salary advance or employee loan under company policy.', 'Apply for an advance or loan with agreed repayment terms.', ARRAY['You qualify under company policy', 'You understand repayment terms'], ARRAY['You need a business expense reimbursed — use Expense claim'], ARRAY['Amount', 'Reason', 'Repayment preference', 'Manager approval if required']),
  ('c0000000-0000-4000-8000-000000000048', 'Desk / Workspace Booking', 'Book a desk', 'Reserve a desk or workspace at the office.', 'Book a seat for yourself or a visitor on specific days.', ARRAY['You need a desk on a particular day', 'A visitor needs workspace'], ARRAY['You only need a meeting room'], ARRAY['Office location', 'Date(s)', 'Number of people', 'Special requirements']),
  ('c0000000-0000-4000-8000-000000000049', 'Travel Request', 'Business travel', 'Request approval and booking for business travel.', 'Arrange approved business travel including flights, hotels, or visas if needed.', ARRAY['You need to travel for approved business', 'Bookings or visas may be required'], ARRAY['You only need a local desk — use Book a desk'], ARRAY['Destination and dates', 'Purpose', 'Estimated budget', 'Manager name']),
  ('c0000000-0000-4000-8000-000000000050', 'ID Badge / Access Card', 'ID badge or access card', 'Get a new or replacement building access card.', 'Request an ID badge or update building access on your card.', ARRAY['You are new or lost your card', 'Your access profile changed'], ARRAY['You need digital system access only'], ARRAY['Reason', 'Office location', 'Whether photo is on file', 'Required date']),
  ('c0000000-0000-4000-8000-000000000051', 'Visa / Work Permit Support', 'Visa and work permit', 'Help with visas and work permits for Dubai or Nairobi.', 'Get support for visa applications, renewals, or dependant permits.', ARRAY['You need a new visa or renewal', 'Immigration deadlines are approaching'], ARRAY['You only need business travel booking', 'Your question is answered in the immigration FAQ'], ARRAY['Visa type', 'Nationality and passport details', 'Timeline', 'Supporting documents']),
  ('c0000000-0000-4000-8000-000000000052', 'Business Cards / Stationery', 'Business cards and stationery', 'Order business cards or standard office supplies.', 'Order business cards, stationery, or standard office materials.', ARRAY['You need new business cards or branded stationery', 'Standard supplies are not available locally'], ARRAY['You need equipment or large purchases — use Buy something'], ARRAY['Item type and quantity', 'Delivery location', 'Artwork approval if custom']),
  ('c0000000-0000-4000-8000-000000000053', 'Market Research Request', 'Market research', 'Research a market, segment, or competitor to inform decisions.', 'Commission research or intelligence you do not have in-house.', ARRAY['You need insight before strategy or campaigns', 'You lack data on a market or competitor'], ARRAY['You only need a presentation designed — use Content production'], ARRAY['Research question', 'Market or segment', 'How you will use results', 'Deadline']),
  ('c0000000-0000-4000-8000-000000000054', 'Brand Asset Request', 'Brand assets', 'Logos, templates, and on-brand materials.', 'Get approved brand assets for events, decks, or campaigns.', ARRAY['You need on-brand materials', 'Existing library assets do not fit'], ARRAY['Suitable assets already exist in the brand library'], ARRAY['Asset type', 'How you will use it', 'Format and size', 'Required date']),
  ('c0000000-0000-4000-8000-000000000055', 'Campaign Request', 'Marketing campaign', 'Plan and run a marketing campaign with specialist support.', 'Launch a coordinated campaign across channels with creative and execution help.', ARRAY['You are running a multi-channel campaign', 'You need end-to-end campaign support'], ARRAY['You only need one asset — use Brand assets or Content production'], ARRAY['Campaign goal', 'Target audience', 'Channels', 'Timeline and budget range']),
  ('c0000000-0000-4000-8000-000000000056', 'Content / Story Production', 'Content production', 'Articles, stories, and thought leadership content.', 'Produce content for campaigns, accounts, or publications.', ARRAY['You need written or multimedia content', 'Content supports a campaign or account plan'], ARRAY['You need full campaign strategy — use Marketing campaign'], ARRAY['Topic and audience', 'Format', 'Key messages', 'Publication date']),
  ('c0000000-0000-4000-8000-000000000057', 'Lead Generation Request', 'Lead generation', 'Run a programme to bring in new sales leads.', 'Launch lead generation for a product, region, or offer.', ARRAY['You need new leads for pipeline', 'Targeting and offers are defined'], ARRAY['You already have leads to qualify — use Qualify leads'], ARRAY['Product or offer', 'Target segment', 'Volume or goal', 'Launch window']),
  ('c0000000-0000-4000-8000-000000000058', 'CX Improvement Request', 'Customer experience improvement', 'Improve how customers experience a journey or touchpoint.', 'Get help redesigning or fixing a customer experience issue.', ARRAY['Customers report friction in a journey', 'You want to improve a touchpoint'], ARRAY['A customer reported a specific fault — use Customer support case'], ARRAY['Customer segment or account', 'Journey or touchpoint', 'Known issues', 'How you will measure success']),
  ('c0000000-0000-4000-8000-000000000059', 'Lead Qualification', 'Qualify leads', 'Score and qualify leads before sales handoff.', 'Have inbound or outbound leads reviewed against your criteria.', ARRAY['Leads need scoring or qualification', 'You have a list ready to review'], ARRAY['You need new leads generated — use Lead generation'], ARRAY['Lead source', 'Number of leads', 'Qualification criteria', 'CRM reference if any']),
  ('c0000000-0000-4000-8000-000000000060', 'Opportunity Registration', 'Register sales opportunity', 'Add a qualified opportunity to the sales pipeline.', 'Register an opportunity with correct stage, value, and owner in CRM.', ARRAY['A qualified deal is ready for the pipeline', 'CRM record needs to be created or corrected'], ARRAY['Leads are not qualified yet — use Qualify leads'], ARRAY['Account name', 'Estimated value and close date', 'Opportunity owner', 'Products or services']),
  ('c0000000-0000-4000-8000-000000000061', 'Sales Support / Proposal', 'Proposal support', 'Help building a sales proposal or bid.', 'Get support with proposal content, pricing, or deal desk input.', ARRAY['You are preparing a proposal with a deadline', 'You need specialist sales support'], ARRAY['The opportunity is not registered — register it first'], ARRAY['Opportunity name', 'Proposal due date', 'Scope summary', 'Known decision criteria']),
  ('c0000000-0000-4000-8000-000000000062', 'Account Setup / Review', 'Customer account setup', 'Set up or review a customer account plan.', 'Configure a new customer account or run a structured account review.', ARRAY['A new customer needs account setup', 'You want a formal account review'], ARRAY['You are onboarding a partner — use Partner onboarding'], ARRAY['Account name', 'Primary contacts', 'Services in scope', 'Review or setup date']),
  ('c0000000-0000-4000-8000-000000000063', 'Partner Onboarding', 'Partner onboarding', 'Onboard a new partner or alliance.', 'Register and enable a partner in systems and ways of working.', ARRAY['A partner agreement is signed or near signature', 'Partner needs to be enabled to sell or deliver'], ARRAY['The party is a customer — use Customer account setup'], ARRAY['Partner name', 'Partnership type', 'Primary contact', 'Target go-live date']),
  ('c0000000-0000-4000-8000-000000000064', 'Ecosystem Engagement Request', 'Partnership engagement', 'Engage platforms, alliances, or ecosystem partners.', 'Coordinate a strategic engagement outside standard partner onboarding.', ARRAY['You are pursuing a strategic alliance or ecosystem deal', 'Multiple teams need to coordinate'], ARRAY['Standard partner onboarding covers your need'], ARRAY['Organisation name', 'Engagement goal', 'Internal sponsor', 'Timeline']),
  ('c0000000-0000-4000-8000-000000000065', 'Customer Onboarding Setup', 'Customer onboarding', 'Prepare a new customer to receive service.', 'Set up access, data, and runbooks so a new customer can go live.', ARRAY['Contract is signed and kick-off is scheduled', 'Customer needs to be ready on go-live date'], ARRAY['The sale is still in pipeline — complete account setup first'], ARRAY['Customer name', 'Services purchased', 'Go-live date', 'Customer contact']),
  ('c0000000-0000-4000-8000-000000000066', 'Order Fulfilment Request', 'Fulfil customer order', 'Deliver an approved customer order or contractual item.', 'Execute and track fulfilment of a customer order to completion.', ARRAY['An order is approved and ready to deliver', 'You need tracked fulfilment'], ARRAY['The order is not approved or funded yet'], ARRAY['Customer and order reference', 'Deliverable description', 'Due date', 'Delivery owner']),
  ('c0000000-0000-4000-8000-000000000067', 'Customer Support Case', 'Customer support case', 'Log an issue or request from a customer.', 'Create a tracked support case with agreed response times.', ARRAY['A customer reported a problem or needs help', 'The case needs formal tracking'], ARRAY['The issue is internal only — use Log an incident'], ARRAY['Customer name', 'Issue summary', 'Severity', 'Contact details']),
  ('c0000000-0000-4000-8000-000000000068', 'Case Setup / Routing', 'Set up case routing', 'Configure how customer cases are routed and escalated.', 'Set up queues and routing rules for a customer or product.', ARRAY['A new product or team needs case management setup', 'Routing rules have changed'], ARRAY['You are logging one customer issue — use Customer support case'], ARRAY['Customer or product', 'Routing rules needed', 'Queues and owners', 'Effective date']),
  ('c0000000-0000-4000-8000-000000000069', 'Incident Escalation', 'Escalate incident', 'Escalate a urgent customer or production incident.', 'Bring urgent incidents to the right people when impact is high or SLA is at risk.', ARRAY['Impact is high or SLA is at risk', 'Normal support path is not enough'], ARRAY['Low-priority query — use Customer support case'], ARRAY['Incident reference if any', 'Customer impact', 'What was tried', 'Response needed by']),
  ('c0000000-0000-4000-8000-000000000070', 'Lifecycle / Renewal Request', 'Renewal or lifecycle change', 'Manage renewals, upgrades, or contract changes for a customer.', 'Coordinate lifecycle events such as renewals or contract changes.', ARRAY['A renewal or expansion window is open', 'Customer lifecycle stage needs action'], ARRAY['You are onboarding a brand-new customer — use Customer onboarding'], ARRAY['Customer name', 'Event type', 'Contract end or renewal date', 'Commercial owner']),
  ('c0000000-0000-4000-8000-000000000071', 'Product Build Request', 'Build product feature', 'Request development or enhancement of a product capability.', 'Start build work for an approved product feature or enhancement.', ARRAY['A backlog item is approved for build', 'Requirements and acceptance criteria exist'], ARRAY['You need a custom customer solution — use Solution delivery'], ARRAY['Product name', 'Feature description', 'Priority', 'Target release']),
  ('c0000000-0000-4000-8000-000000000072', 'Solution Delivery Engagement', 'Solution delivery', 'Engage a team to design and deliver a customer solution.', 'Run a multi-step solution engagement for a customer programme.', ARRAY['You need a tailored solution for a customer', 'Design and delivery phases are in scope'], ARRAY['A small product change is enough — use Build product feature'], ARRAY['Customer name', 'Problem statement', 'Scope boundaries', 'Target milestones']),
  ('c0000000-0000-4000-8000-000000000073', 'Project Setup Request', 'Set up delivery project', 'Stand up a new delivery project with governance and team.', 'Create project structure, resourcing, and controls for approved work.', ARRAY['Funding or statement of work is approved', 'You need a project formally set up'], ARRAY['Ongoing managed operations cover the need — use Managed services'], ARRAY['Project name', 'Sponsor', 'Start date', 'Scope and budget summary']),
  ('c0000000-0000-4000-8000-000000000074', 'Managed Services Request', 'Managed services', 'Request ongoing managed operations for a customer or platform.', 'Start a managed service with defined scope and service levels.', ARRAY['You need ongoing run support with SLAs', 'Scope and service levels are defined'], ARRAY['Fixed-scope project delivery is enough — use Set up delivery project'], ARRAY['Service scope', 'SLA targets', 'Customer or platform', 'Contract reference']),
  ('c0000000-0000-4000-8000-000000000075', 'Production Operations Support', 'Production support', 'Help with live systems and production operations.', 'Get support for production issues, deployments, or platform operations.', ARRAY['Production needs urgent or specialist support', 'You need deployment or monitoring help'], ARRAY['Work is still in build phase — use Build product feature or Set up project'], ARRAY['Environment', 'System or service name', 'Issue or change description', 'Urgency']),
  ('c0000000-0000-4000-8000-000000000076', 'Delivery Performance Review', 'Delivery performance review', 'Review delivery KPIs and improvement actions.', 'Assess how well delivery is performing against targets and agree next steps.', ARRAY['A review or QBR needs performance evidence', 'You want an independent read on delivery health'], ARRAY['You need a one-off incident report — use Escalate incident'], ARRAY['Programme or team name', 'Period under review', 'KPIs or scorecard', 'Review date']);

UPDATE discovery.listings l
SET title = u.display_name, summary = u.short_description
FROM _ux_display u WHERE l.id = u.listing_id;

UPDATE discovery.service_details sd
SET
  purpose = u.purpose,
  when_to_use = u.when_to_use,
  when_not_to_use = u.when_not_to_use,
  required_inputs = u.required_inputs
FROM _ux_display u WHERE sd.listing_id = u.listing_id;

INSERT INTO discovery.listing_attributes (tenant_id, listing_id, key, value, data_type, sort_order)
SELECT 'a0000000-0000-4000-8000-000000000001', u.listing_id, 'service_name', u.service_name, 'text', 1
FROM _ux_display u
ON CONFLICT (listing_id, key) DO UPDATE SET value = EXCLUDED.value;

INSERT INTO discovery.listing_attributes (tenant_id, listing_id, key, value, data_type, sort_order)
SELECT 'a0000000-0000-4000-8000-000000000001', l.id, 'primary_action_label', 'Request Service', 'text', 2
FROM discovery.listings l
WHERE l.marketplace_id = 'b0000000-0000-4000-8000-000000000004'
ON CONFLICT (listing_id, key) DO UPDATE SET value = EXCLUDED.value;

COMMIT;

-- CHECKPOINT
-- SELECT l.title, la.value AS primary_action FROM discovery.listings l
-- JOIN discovery.listing_attributes la ON la.listing_id = l.id AND la.key = 'primary_action_label' LIMIT 5;
